name: Registry docker image to ECR
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  push:
    branches:
      - main
    paths:
      - ./**
      - .github/workflows/main.yml

env:
  REPO_NAME: product-a
  ECR_REGION: ap-northeast-1
  AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
  IAM_ROLE_ARN: ${{ secrets.IAM_ROLE_ARN }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.ECR_REGION }}
          role-to-assume: ${{ env.IAM_ROLE_ARN}}

      - name: Login to ECR
        uses: docker/login-action@v1
        env:
          ECR_REGISTRY: ${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.ECR_REGION }}.amazonaws.com
        with:
          registry: ${{ env.ECR_REGISTRY }}

      - name: Docker build and push to ECR
        uses: docker/build-push-action@v2
        env:
          ECR_REPOSITORY: ${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.ECR_REGION }}.amazonaws.com/${{ env.REPO_NAME }}
        with:
          push: true
          file: .github/Dockerfile
          tags: |
            ${{ env.ECR_REPOSITORY }}:latest
            ${{ env.ECR_REPOSITORY }}:${{ github.sha }}

